const CARS_DATA = [
    {
        id: "genesis-g80-2023",
        brand: "Genesis",
        model: "G80 2.5T AWD",
        year: 2023,
        mileage: 18500,
        price: 43500,
        condition: "Used",
        fuel: "Gasoline",
        transmission: "Automatic",
        engine: "2,497 cc Turbocharged 4-Cylinder",
        color: "Metallic Silver",
        driveType: "AWD",
        features: ["Leather Seats", "Panoramic Sunroof", "Lane Keep Assist", "360 Camera", "Heated/Cooled Seats", "Head-up Display"],
        image: "images/genesis_g80.jpg",
        description: "A highly luxurious Genesis G80 in pristine condition, directly sourced from Seoul. Packed with premium executive features, outstanding safety ratings, and low mileage. Single owner, no accident history, fully inspected."
    },
    {
        id: "hyundai-palisade-2022",
        brand: "Hyundai",
        model: "Palisade 2.2 Diesel Prestige",
        year: 2022,
        mileage: 38000,
        price: 29800,
        condition: "Used",
        fuel: "Diesel",
        transmission: "Automatic",
        engine: "2,199 cc CRDi Diesel 4-Cylinder",
        color: "Dark Blue",
        driveType: "4WD",
        features: ["7 Seats", "Smart Cruise Control", "Power Tailgate", "Tri-zone Climate Control", "Apple CarPlay", "Blind Spot Monitor"],
        image: "images/hyundai_palisade.jpg",
        description: "Perfect family SUV with 3rd-row seating. Sourced from Incheon, Korea. Exceptionally clean interior, robust diesel engine with great fuel efficiency for long trips. Ready for shipment immediately."
    },
    {
        id: "kia-ev6-2023",
        brand: "Kia",
        model: "EV6 GT-Line",
        year: 2023,
        mileage: 12000,
        price: 36500,
        condition: "Used",
        fuel: "Electric",
        transmission: "Automatic",
        engine: "Dual Motor / 77.4 kWh Battery (320 HP)",
        color: "Matte Gray",
        driveType: "AWD",
        features: ["Super-fast 800V Charging", "Augmented Reality HUD", "Meridian Sound System", "Ventilated Front Seats", "V2L Capability"],
        image: "images/kia_ev6.jpg",
        description: "Top-tier electric vehicle with low mileage. Under factory warranty in Korea. Ultra-modern EV charging technology, high performance AWD drive, and extremely low running costs. Clean title, perfect condition."
    },
    {
        id: "hyundai-elantra-2024",
        brand: "Hyundai",
        model: "Elantra (Avante) 1.6 Modern",
        year: 2024,
        mileage: 0,
        price: 18200,
        condition: "New",
        fuel: "Gasoline",
        transmission: "Automatic",
        engine: "1,598 cc Smartstream 4-Cylinder",
        color: "Polar White",
        driveType: "FWD",
        features: ["LED Headlights", "Digital Gauge Cluster", "Lane Centering Assist", "Wireless Charging", "Heated Steering Wheel"],
        image: "images/genesis_g80.jpg",
        description: "Brand new Hyundai Avante (exported worldwide as Elantra). Extremely popular sedan, highly reliable, superb fuel economy, and affordable pricing. Direct from the factory."
    },
    {
        id: "kia-sportage-2021",
        brand: "Kia",
        model: "Sportage 1.6 Turbo Hybrid Signature",
        year: 2021,
        mileage: 52000,
        price: 22400,
        condition: "Used",
        fuel: "Hybrid",
        transmission: "Automatic",
        engine: "1,598 cc Turbocharged Hybrid",
        color: "Gravity Gray",
        driveType: "FWD",
        features: ["Panoramic Display", "Forward Collision Avoidance", "Heated Steering Wheel", "Dual Zone Climate", "Smart Keyless Entry"],
        image: "images/kia_ev6.jpg",
        description: "Highly efficient hybrid SUV. Perfect combination of daily practicality, high fuel economy (over 16 km/l), and modern tech interface. Sourced from Busan, fully serviced, pristine conditions."
    },
    {
        id: "genesis-gv80-2024",
        brand: "Genesis",
        model: "GV80 3.5T Luxury Sport",
        year: 2024,
        mileage: 0,
        price: 68500,
        condition: "New",
        fuel: "Gasoline",
        transmission: "Automatic",
        engine: "3,470 cc Twin-Turbo V6 (375 HP)",
        color: "Vik Black",
        driveType: "AWD",
        features: ["Nappa Leather Seats", "Road Active Noise Control", "Electronically Controlled Suspension", "22-inch Wheels", "Soft-Close Doors"],
        image: "images/hyundai_palisade.jpg",
        description: "Brand new high-performance luxury SUV. Executive comfort with powerful twin-turbo V6 engine, custom-ordered from Genesis South Korea. Shipped on premium RORO vessel."
    }
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = CARS_DATA;
}
