CARS = [
    {
        "id": 1,
        "brand": "Genesis",
        "model": "G80",
        "year": 2023,
        "mileage": 12000,
        "price": 52000,
        "condition": "Used",
        "status": "Available",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "2.5L Turbo",
        "color": "Black",
        "driveType": "AWD",
        "bodyType": "sedan",
        "features": [
            "Leather Seats",
            "Panoramic Sunroof",
            "Adaptive Cruise Control",
            "Head-Up Display",
            "12.3\" Infotainment Screen"
        ],
        "image": "images/genesis_g80.jpg",
        "description": "Premium luxury sedan with refined ride quality and cutting-edge driver assistance technology. Well-maintained with full Genesis service history."
    },
    {
        "id": 2,
        "brand": "Genesis",
        "model": "GV80",
        "year": 2023,
        "mileage": 14000,
        "price": 62500,
        "condition": "Used",
        "status": "Available",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "3.5L Twin-Turbo V6",
        "color": "Cardiff Green",
        "driveType": "AWD",
        "bodyType": "suv",
        "features": [
            "Ergo Motion Driver Seat",
            "Lexicon 21-Speaker Audio",
            "Surround View Monitor",
            "Power Folding 3rd Row",
            "Electronic Controlled Suspension"
        ],
        "image": "images/hyundai_palisade.jpg",
        "description": "Mid-size luxury SUV combining commanding road presence with an impeccably crafted interior. The pinnacle of Genesis SUV craftsmanship."
    },
    {
        "id": 3,
        "brand": "Genesis",
        "model": "G70",
        "year": 2023,
        "mileage": 9000,
        "price": 39500,
        "condition": "Used",
        "status": "Sold",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "2.0L Turbo",
        "color": "Havana Red",
        "driveType": "RWD",
        "bodyType": "sedan",
        "features": [
            "Sport-Tuned Suspension",
            "Brembo Brakes",
            "Lexicon Premium Audio",
            "8\" Touchscreen with Navigation",
            "Launch Control"
        ],
        "image": "images/genesis_g80.jpg",
        "description": "Sports sedan that earned North American Car of the Year honors. Rear-wheel drive dynamics with luxury appointments at every turn."
    },
    {
        "id": 4,
        "brand": "Genesis",
        "model": "G90",
        "year": 2024,
        "mileage": 3000,
        "price": 88000,
        "condition": "Used",
        "status": "Available",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "3.5L Twin-Turbo e-Supercharger",
        "color": "Vik Black",
        "driveType": "AWD",
        "bodyType": "sedan",
        "features": [
            "VIP Executive Rear Seating",
            "Bang & Olufsen 3D Sound",
            "EasyClose Power Doors",
            "Multi-Chamber Air Suspension",
            "Rear Seat Massagers"
        ],
        "image": "images/genesis_g80.jpg",
        "description": "The ultimate Korean flagship limousine. Unsurpassed tranquility, elite executive comfort, and highest-tier Korean diplomatic luxury."
    },
    {
        "id": 5,
        "brand": "Genesis",
        "model": "GV70",
        "year": 2024,
        "mileage": 0,
        "price": 54000,
        "condition": "New",
        "status": "Available",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "2.5L Turbo GDi",
        "color": "Uyuni White",
        "driveType": "AWD",
        "bodyType": "suv",
        "features": [
            "Sport Prestige Package",
            "14.5\" HD Navigation",
            "Blind-Spot View Monitor",
            "Panoramic Roof",
            "Smart Cruise Control 2"
        ],
        "image": "images/hyundai_palisade.jpg",
        "description": "Dynamic compact luxury crossover offering spirited performance, aviation-inspired cabin design, and cutting-edge safety features."
    },
    {
        "id": 6,
        "brand": "Genesis",
        "model": "GV60",
        "year": 2023,
        "mileage": 11000,
        "price": 49000,
        "condition": "Used",
        "status": "Sold",
        "fuel": "Electric",
        "transmission": "Automatic",
        "engine": "Dual Motor Performance EV",
        "color": "Sao Paulo Lime",
        "driveType": "AWD",
        "bodyType": "electric",
        "features": [
            "Crystal Sphere Shifter",
            "Face Connect & Fingerprint Auth",
            "Boost Mode 483 HP",
            "Drift Mode",
            "B&O Premium Audio"
        ],
        "image": "images/kia_ev6.jpg",
        "description": "Avant-garde electric performance crossover built on E-GMP. Features futuristic biometric recognition and instant neck-snapping acceleration."
    },
    {
        "id": 7,
        "brand": "Hyundai",
        "model": "Palisade",
        "year": 2024,
        "mileage": 0,
        "price": 48500,
        "condition": "New",
        "status": "Available",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "3.8L V6",
        "color": "White",
        "driveType": "AWD",
        "bodyType": "suv",
        "features": [
            "7-Passenger Seating",
            "Nappa Leather Interior",
            "Blind-Spot View Monitor",
            "Harman Kardon Audio",
            "Power Tailgate"
        ],
        "image": "images/hyundai_palisade.jpg",
        "description": "Flagship full-size SUV offering three-row seating and a premium cabin. Ideal for families seeking comfort and space."
    },
    {
        "id": 8,
        "brand": "Hyundai",
        "model": "Elantra",
        "year": 2022,
        "mileage": 35000,
        "price": 18500,
        "condition": "Used",
        "status": "Available",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "2.0L MPI",
        "color": "Silver",
        "driveType": "FWD",
        "bodyType": "sedan",
        "features": [
            "10.25\" Touchscreen",
            "Wireless Apple CarPlay",
            "Smart Key with Push Start",
            "Lane Keep Assist"
        ],
        "image": "images/genesis_g80.jpg",
        "description": "Sleek and fuel-efficient compact sedan with a striking angular design. A practical daily driver with modern tech features."
    },
    {
        "id": 9,
        "brand": "Hyundai",
        "model": "Sonata",
        "year": 2024,
        "mileage": 0,
        "price": 28500,
        "condition": "New",
        "status": "Available",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "1.6L Turbo GDi",
        "color": "Abyss Black Pearl",
        "driveType": "FWD",
        "bodyType": "sedan",
        "features": [
            "Panoramic Curved Display",
            "Column-Type Shift By Wire",
            "Wireless Phone Charging",
            "Hyundai SmartSense ADAS"
        ],
        "image": "images/genesis_g80.jpg",
        "description": "The reimagined Sonata 'The Edge' brings a futuristic seamless horizon lamp and unmatched mid-size executive sedan refinement."
    },
    {
        "id": 10,
        "brand": "Hyundai",
        "model": "Grandeur (Azera)",
        "year": 2023,
        "mileage": 18000,
        "price": 38000,
        "condition": "Used",
        "status": "Sold",
        "fuel": "Hybrid",
        "transmission": "Automatic",
        "engine": "1.6L Turbo Hybrid",
        "color": "Curator Silver Metallic",
        "driveType": "FWD",
        "bodyType": "hybrid",
        "features": [
            "Seamless Horizon Lamp",
            "Frameless Doors",
            "Bose Premium Sound",
            "Dual 12.3\" Screens",
            "Rear Executive Comfort Seats"
        ],
        "image": "images/genesis_g80.jpg",
        "description": "Korea's number one best-selling premium sedan. Blends royal heritage with high-tech hybrid efficiency and whisper-quiet ride."
    },
    {
        "id": 11,
        "brand": "Hyundai",
        "model": "Tucson",
        "year": 2023,
        "mileage": 22000,
        "price": 27500,
        "condition": "Used",
        "status": "Available",
        "fuel": "Diesel",
        "transmission": "Automatic",
        "engine": "2.0L CRDi",
        "color": "Amazon Gray",
        "driveType": "AWD",
        "bodyType": "suv",
        "features": [
            "Parametric Hidden Lights",
            "Multi-Air Mode AC",
            "Heated & Ventilated Seats",
            "HTRAC All-Wheel Drive"
        ],
        "image": "images/hyundai_palisade.jpg",
        "description": "Global hit compact SUV offering distinctive parametric jewel styling, punchy torque, and remarkable fuel economy."
    },
    {
        "id": 12,
        "brand": "Hyundai",
        "model": "Santa Fe",
        "year": 2024,
        "mileage": 0,
        "price": 42000,
        "condition": "New",
        "status": "Available",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "2.5L Turbo GDi",
        "color": "Terracotta Orange",
        "driveType": "AWD",
        "bodyType": "suv",
        "features": [
            "Boxy Outdoor Lifestyle Design",
            "Dual Wireless Fast Chargers",
            "UV-C Sterilization Tray",
            "Class-Leading Cargo Volume"
        ],
        "image": "images/hyundai_palisade.jpg",
        "description": "All-new 5th generation Santa Fe. Radical rugged design tailored for urban commutes and off-grid camping adventures."
    },
    {
        "id": 13,
        "brand": "Hyundai",
        "model": "Staria Lounge",
        "year": 2023,
        "mileage": 25000,
        "price": 37500,
        "condition": "Used",
        "status": "Sold",
        "fuel": "Diesel",
        "transmission": "Automatic",
        "engine": "2.2L CRDi Diesel",
        "color": "Creamy White",
        "driveType": "AWD",
        "bodyType": "van",
        "features": [
            "7-Seat VIP Relaxation Seats",
            "Panoramic Windows",
            "Bose Audio",
            "Dual Power Sliding Doors",
            "Smart Power Tailgate"
        ],
        "image": "images/hyundai_palisade.jpg",
        "description": "Spaceship-inspired premium MPV. The most luxurious passenger van Korea produces, favored by touring VIPs and big families."
    },
    {
        "id": 14,
        "brand": "Hyundai",
        "model": "Ioniq 5",
        "year": 2023,
        "mileage": 16000,
        "price": 38500,
        "condition": "Used",
        "status": "Available",
        "fuel": "Electric",
        "transmission": "Automatic",
        "engine": "77.4 kWh AWD Long Range",
        "color": "Gravity Gold Matte",
        "driveType": "AWD",
        "bodyType": "electric",
        "features": [
            "Parametric Pixel Lighting",
            "Universal Island Sliding Console",
            "V2L Power Outlet",
            "Relaxation Zero-Gravity Seats"
        ],
        "image": "images/kia_ev6.jpg",
        "description": "World Car of the Year winner. Retro-futuristic hatchback-crossover with blazing 800V fast charging."
    },
    {
        "id": 15,
        "brand": "Hyundai",
        "model": "Ioniq 6",
        "year": 2024,
        "mileage": 5000,
        "price": 43000,
        "condition": "Used",
        "status": "Available",
        "fuel": "Electric",
        "transmission": "Automatic",
        "engine": "77.4 kWh AWD Electrified Streamliner",
        "color": "Biophilic Blue Pearl",
        "driveType": "AWD",
        "bodyType": "electric",
        "features": [
            "0.21 Ultra-Low Drag Coefficient",
            "Dual Color Ambient Lighting",
            "Speed-Sync Interior Mood Lights",
            "Digital Side Mirrors"
        ],
        "image": "images/kia_ev6.jpg",
        "description": "Aerodynamic electrified streamliner with over 540km single-charge range and bespoke high-speed cruise stability."
    },
    {
        "id": 16,
        "brand": "Hyundai",
        "model": "Porter II",
        "year": 2021,
        "mileage": 78000,
        "price": 9800,
        "condition": "Used",
        "status": "Sold",
        "fuel": "Diesel",
        "transmission": "Manual",
        "engine": "2.5L CRDi Turbo Diesel",
        "color": "Solid Blue",
        "driveType": "RWD",
        "bodyType": "truck",
        "features": [
            "1-Ton Double Cab",
            "Air Conditioning",
            "Power Steering",
            "Reinforced Leaf Springs",
            "PTO Installed"
        ],
        "image": "images/genesis_g80.jpg",
        "description": "The workhorse of South Korea. Highly sought after worldwide for bulletproof reliability, cheap maintenance, and tough utility."
    },
    {
        "id": 17,
        "brand": "Hyundai",
        "model": "Kona Electric",
        "year": 2024,
        "mileage": 0,
        "price": 34000,
        "condition": "New",
        "status": "Available",
        "fuel": "Electric",
        "transmission": "Automatic",
        "engine": "65.4 kWh Long Range",
        "color": "Cyber Gray Metallic",
        "driveType": "FWD",
        "bodyType": "compact",
        "features": [
            "Pixelated Seamless Horizon",
            "Vehicle-to-Load (V2L)",
            "Smart Regenerative Braking",
            "Heads-Up Display"
        ],
        "image": "images/kia_ev6.jpg",
        "description": "EV-first compact crossover designed for modern city streets with exceptional efficiency and roomy futuristic cabin."
    },
    {
        "id": 18,
        "brand": "Kia",
        "model": "EV6",
        "year": 2024,
        "mileage": 0,
        "price": 55000,
        "condition": "New",
        "status": "Available",
        "fuel": "Electric",
        "transmission": "Automatic",
        "engine": "Dual Motor Electric",
        "color": "Gravity Blue",
        "driveType": "AWD",
        "bodyType": "electric",
        "features": [
            "800V Ultra-Fast Charging",
            "Augmented Reality HUD",
            "Vehicle-to-Load (V2L)",
            "Meridian Premium Audio",
            "Remote Smart Parking"
        ],
        "image": "images/kia_ev6.jpg",
        "description": "Award-winning all-electric crossover with 800V architecture enabling 10–80% charge in just 18 minutes. Bold design meets zero-emission performance."
    },
    {
        "id": 19,
        "brand": "Kia",
        "model": "Sportage",
        "year": 2023,
        "mileage": 20000,
        "price": 29000,
        "condition": "Used",
        "status": "Available",
        "fuel": "Hybrid",
        "transmission": "Automatic",
        "engine": "1.6L Turbo Hybrid",
        "color": "Steel Gray",
        "driveType": "AWD",
        "bodyType": "hybrid",
        "features": [
            "Curved Panoramic Display",
            "Wireless Smartphone Integration",
            "Smart Cruise Control",
            "Terrain Mode"
        ],
        "image": "images/kia_ev6.jpg",
        "description": "Compact crossover balancing bold exterior styling with a tech-forward cabin. Exceptional fuel economy with punchy turbocharged hybrid power."
    },
    {
        "id": 20,
        "brand": "Kia",
        "model": "Carnival Limousine",
        "year": 2024,
        "mileage": 4000,
        "price": 49500,
        "condition": "Used",
        "status": "Sold",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "3.5L V6 GDi",
        "color": "Snow White Pearl",
        "driveType": "FWD",
        "bodyType": "van",
        "features": [
            "Hi-Limousine High Roof",
            "29\" Smart Monitor",
            "VIP Ottoman Massaging Seats",
            "Built-In Air Purifier",
            "Mood Lighting"
        ],
        "image": "images/hyundai_palisade.jpg",
        "description": "Korea's undisputed King of luxury vans. High-roof custom spec with first-class airline seats and personal smart entertainment suite."
    },
    {
        "id": 21,
        "brand": "Kia",
        "model": "Sorento",
        "year": 2023,
        "mileage": 16000,
        "price": 36000,
        "condition": "Used",
        "status": "Available",
        "fuel": "Hybrid",
        "transmission": "Automatic",
        "engine": "1.6L Turbo Hybrid",
        "color": "Gravity Gray",
        "driveType": "AWD",
        "bodyType": "hybrid",
        "features": [
            "Three-Row Seating",
            "10.25\" Navigation System",
            "Smart Power Tailgate",
            "Highway Driving Assist 2",
            "Multi-Terrain AWD"
        ],
        "image": "images/hyundai_palisade.jpg",
        "description": "Mid-size SUV with hybrid efficiency and genuine three-row versatility. Excellent fuel economy without sacrificing space or capability."
    },
    {
        "id": 22,
        "brand": "Kia",
        "model": "K5",
        "year": 2023,
        "mileage": 28000,
        "price": 23500,
        "condition": "Used",
        "status": "Available",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "1.6L Turbo",
        "color": "Wolf Gray",
        "driveType": "FWD",
        "bodyType": "sedan",
        "features": [
            "Heartbeat DRL Signature",
            "Rotary Gear Shift",
            "Panoramic Glass Sunroof",
            "Sport Drive Modes"
        ],
        "image": "images/genesis_g80.jpg",
        "description": "Aggressive fastback sports sedan silhouette with sharp handling dynamics and class-leading cabin tech."
    },
    {
        "id": 23,
        "brand": "Kia",
        "model": "K8",
        "year": 2023,
        "mileage": 19000,
        "price": 34500,
        "condition": "Used",
        "status": "Sold",
        "fuel": "Hybrid",
        "transmission": "Automatic",
        "engine": "1.6L Turbo Hybrid",
        "color": "Deep Chroma Blue",
        "driveType": "FWD",
        "bodyType": "hybrid",
        "features": [
            "Star Cloud Frameless Grille",
            "Meridian 14-Speaker Sound",
            "Ergo Motion Seating",
            "Electronic Suspension"
        ],
        "image": "images/genesis_g80.jpg",
        "description": "Executive mid-luxury sedan with diamond-pattern detailing and whisper-quiet hybrid road manners."
    },
    {
        "id": 24,
        "brand": "Kia",
        "model": "K9 (K900)",
        "year": 2022,
        "mileage": 31000,
        "price": 44000,
        "condition": "Used",
        "status": "Available",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "3.3L Twin-Turbo V6",
        "color": "Aurora Black Pearl",
        "driveType": "AWD",
        "bodyType": "sedan",
        "features": [
            "Preview Electronic Suspension",
            "Lexicon 3D Sound",
            "Rear Dual VIP Displays",
            "Soft-Close Doors"
        ],
        "image": "images/genesis_g80.jpg",
        "description": "Understated ultra-luxury flagship sedan offering German-rivaling craftsmanship at exceptional export value."
    },
    {
        "id": 25,
        "brand": "Kia",
        "model": "EV9",
        "year": 2024,
        "mileage": 0,
        "price": 72000,
        "condition": "New",
        "status": "Available",
        "fuel": "Electric",
        "transmission": "Automatic",
        "engine": "99.8 kWh Dual Motor AWD",
        "color": "Ocean Blue Matte",
        "driveType": "AWD",
        "bodyType": "electric",
        "features": [
            "3-Row Swivel Seats",
            "Digital Pattern Lighting Grille",
            "Highway Driving Pilot",
            "Terrain Mode All-Electric"
        ],
        "image": "images/kia_ev6.jpg",
        "description": "Massive 3-row flagship electric SUV. High-torque electric capability, supreme interior room, and standout geometric styling."
    },
    {
        "id": 26,
        "brand": "Kia",
        "model": "Morning (Picanto)",
        "year": 2021,
        "mileage": 42000,
        "price": 7500,
        "condition": "Used",
        "status": "Available",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "1.0L MPI",
        "color": "Honey Bee Yellow",
        "driveType": "FWD",
        "bodyType": "compact",
        "features": [
            "Compact City Dimensions",
            "Rear Parking Sensors",
            "Heated Steering Wheel",
            "Excellent 15.7 km/L Fuel Economy"
        ],
        "image": "images/kia_ev6.jpg",
        "description": "Korea's most beloved city subcompact. Extremely economical to run, easy to park, and ultra-durable for courier or city life."
    },
    {
        "id": 27,
        "brand": "Kia",
        "model": "Bongo III",
        "year": 2020,
        "mileage": 110000,
        "price": 8500,
        "condition": "Used",
        "status": "Sold",
        "fuel": "Diesel",
        "transmission": "Manual",
        "engine": "2.5L CRDi Diesel",
        "color": "White",
        "driveType": "RWD",
        "bodyType": "truck",
        "features": [
            "1-Ton Payload Capacity",
            "Drop-Side Cargo Bed",
            "Power Windows",
            "Air Conditioning"
        ],
        "image": "images/genesis_g80.jpg",
        "description": "Korea's best-selling light commercial truck, essential for small businesses. Legendary durability and low operating costs."
    },
    {
        "id": 28,
        "brand": "Kia",
        "model": "Mohave Master",
        "year": 2022,
        "mileage": 39000,
        "price": 37000,
        "condition": "Used",
        "status": "Sold",
        "fuel": "Diesel",
        "transmission": "Automatic",
        "engine": "3.0L V6 CRDi Diesel",
        "color": "Steel Gray",
        "driveType": "4WD",
        "bodyType": "suv",
        "features": [
            "Body-on-Frame Chassis",
            "V6 Diesel Heavy Pulling Power",
            "Low-Range 4WD",
            "12.3\" Luxury Cockpit"
        ],
        "image": "images/hyundai_palisade.jpg",
        "description": "True traditional body-on-frame off-road SUV powered by a monster 3.0L V6 diesel engine. Legendary toughness."
    },
    {
        "id": 29,
        "brand": "Chevrolet",
        "model": "Spark",
        "year": 2021,
        "mileage": 48000,
        "price": 6200,
        "condition": "Used",
        "status": "Available",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "1.0L ECOTEC",
        "color": "Mystic Sky Blue",
        "driveType": "FWD",
        "bodyType": "compact",
        "features": [
            "City Car Agility",
            "Apple CarPlay & Android Auto",
            "Rear Camera",
            "High-Strength Steel Cage"
        ],
        "image": "images/genesis_g80.jpg",
        "description": "Built at GM Changwon Korea. Compact, exceptionally fuel-efficient, and easy to maintain worldwide."
    },
    {
        "id": 30,
        "brand": "Chevrolet",
        "model": "Malibu",
        "year": 2022,
        "mileage": 36000,
        "price": 16500,
        "condition": "Used",
        "status": "Available",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "1.35L Turbo E-Turbo",
        "color": "Snow White Pearl",
        "driveType": "FWD",
        "bodyType": "sedan",
        "features": [
            "Active Noise Cancellation",
            "Ventilated Front Seats",
            "Bose 9-Speaker Audio",
            "Low Tax Bracket"
        ],
        "image": "images/genesis_g80.jpg",
        "description": "Mid-size American cruiser built in Korea with impressive highway composure and low-displacement turbo tax savings."
    },
    {
        "id": 31,
        "brand": "Chevrolet",
        "model": "Trax Crossover",
        "year": 2024,
        "mileage": 0,
        "price": 21800,
        "condition": "New",
        "status": "Available",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "1.2L E-Turbo",
        "color": "Fiery Red",
        "driveType": "FWD",
        "bodyType": "compact",
        "features": [
            "RS Sport Styling",
            "11\" Diagonal Display",
            "Wireless Phone Projection",
            "Active Noise Cancellation"
        ],
        "image": "images/kia_ev6.jpg",
        "description": "Massive global export sensation assembled in Bupyeong, Korea. Athletic crossover styling with unmatched cost-to-feature value."
    },
    {
        "id": 32,
        "brand": "Chevrolet",
        "model": "Trailblazer",
        "year": 2023,
        "mileage": 24000,
        "price": 19500,
        "condition": "Used",
        "status": "Sold",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "1.35L Turbo",
        "color": "Monaco Blue Dual Tone",
        "driveType": "AWD",
        "bodyType": "suv",
        "features": [
            "Activ Off-Road Trim",
            "Selectable AWD",
            "Hands-Free Power Liftgate",
            "Panoramic Sunroof"
        ],
        "image": "images/hyundai_palisade.jpg",
        "description": "Punchy Korean-built compact crossover featuring rugged two-tone adventure styling and smart switchable AWD."
    },
    {
        "id": 33,
        "brand": "Chevrolet",
        "model": "Colorado",
        "year": 2022,
        "mileage": 45000,
        "price": 29800,
        "condition": "Used",
        "status": "Available",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "3.6L V6 Naturally Aspirated",
        "color": "Satin Steel Gray",
        "driveType": "4WD",
        "bodyType": "truck",
        "features": [
            "Z71 Off-Road Suspension",
            "Autotrac 4WD Transfer Case",
            "Spray-On Bedliner",
            "Heavy-Duty Towing Package"
        ],
        "image": "images/hyundai_palisade.jpg",
        "description": "Authentic American mid-size pickup widely driven and serviced in Korea. Robust 3.6L V6 engine ready for heavy payload."
    },
    {
        "id": 34,
        "brand": "Renault",
        "model": "SM6 (Talisman)",
        "year": 2022,
        "mileage": 38000,
        "price": 15800,
        "condition": "Used",
        "status": "Available",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "1.3L Turbo TCe",
        "color": "Highland Silver",
        "driveType": "FWD",
        "bodyType": "sedan",
        "features": [
            "Bose Surround Sound",
            "8.7\" Vertical Touchscreen",
            "Massage Front Seats",
            "LED Pure Vision Headlamps"
        ],
        "image": "images/genesis_g80.jpg",
        "description": "French elegance engineered in Busan, South Korea. Known for supreme high-speed stability and luxurious quiet cabin."
    },
    {
        "id": 35,
        "brand": "Renault",
        "model": "QM6 (Koleos)",
        "year": 2023,
        "mileage": 29000,
        "price": 21500,
        "condition": "Used",
        "status": "Available",
        "fuel": "LPG",
        "transmission": "Automatic",
        "engine": "2.0L LPe Eco",
        "color": "Metallic Black",
        "driveType": "FWD",
        "bodyType": "suv",
        "features": [
            "Donut LPG Tank Tech (Full Trunk)",
            "Quilted Nappa Leather",
            "Hands-Free Tailgate",
            "Low Fuel Cost"
        ],
        "image": "images/hyundai_palisade.jpg",
        "description": "South Korea's most popular family SUV with patented donut LPG technology. Unrivaled fuel budget savings with quiet refinement."
    },
    {
        "id": 36,
        "brand": "Renault",
        "model": "XM3 (Arkana)",
        "year": 2023,
        "mileage": 19000,
        "price": 18200,
        "condition": "Used",
        "status": "Sold",
        "fuel": "Hybrid",
        "transmission": "Automatic",
        "engine": "1.6L E-TECH Hybrid",
        "color": "Wave Blue",
        "driveType": "FWD",
        "bodyType": "hybrid",
        "features": [
            "Coupe-SUV Profile",
            "F1 Inspired E-Tech Hybrid",
            "9.3\" Easy Link Screen",
            "Auto Hold & Electronic Parking Brake"
        ],
        "image": "images/kia_ev6.jpg",
        "description": "Sensational coupe-SUV profile offering agile urban handling and F1-derived multi-mode hybrid powertrain."
    },
    {
        "id": 37,
        "brand": "Ssangyong",
        "model": "Torres",
        "year": 2024,
        "mileage": 6000,
        "price": 26500,
        "condition": "Used",
        "status": "Available",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "1.5L Turbo GDi",
        "color": "Forrest Green",
        "driveType": "AWD",
        "bodyType": "suv",
        "features": [
            "Rugged Outdoor Aesthetic",
            "Triple Split Digital Cockpit",
            "703L Massive Trunk Space",
            "Smart AWD Lock"
        ],
        "image": "images/hyundai_palisade.jpg",
        "description": "KGM's breakthrough authentic SUV. Bold retro off-road grille inspired by adventure expeditions."
    },
    {
        "id": 38,
        "brand": "Ssangyong",
        "model": "Rexton",
        "year": 2023,
        "mileage": 31000,
        "price": 31000,
        "condition": "Used",
        "status": "Sold",
        "fuel": "Diesel",
        "transmission": "Automatic",
        "engine": "2.2L e-XDi Diesel",
        "color": "Space Black",
        "driveType": "4WD",
        "bodyType": "suv",
        "features": [
            "Quad-Frame High-Strength Steel",
            "Part-Time 4WD with Low Ratio",
            "3-Ton Towing Capacity",
            "Diamond Quilted Interior"
        ],
        "image": "images/hyundai_palisade.jpg",
        "description": "Full-size flagship quad-frame SUV offering unmatched towing strength, high-grade leather, and military-grade durability."
    },
    {
        "id": 39,
        "brand": "Ssangyong",
        "model": "Musso Grand (Khan)",
        "year": 2022,
        "mileage": 55000,
        "price": 22000,
        "condition": "Used",
        "status": "Available",
        "fuel": "Diesel",
        "transmission": "Automatic",
        "engine": "2.2L e-XDi Turbo Diesel",
        "color": "Marble Gray",
        "driveType": "4WD",
        "bodyType": "truck",
        "features": [
            "Extended Long Bed",
            "Differential Lock (LD)",
            "Heavy Duty Coil Springs",
            "5-Passenger Spacious Crew Cab"
        ],
        "image": "images/hyundai_palisade.jpg",
        "description": "Korea's number one heavy-duty diesel utility pickup. Built on ultra-stiff quad chassis ready for agriculture or construction."
    },
    {
        "id": 40,
        "brand": "Ssangyong",
        "model": "Tivoli",
        "year": 2021,
        "mileage": 42000,
        "price": 12800,
        "condition": "Used",
        "status": "Available",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "1.5L Turbo",
        "color": "Dandy Blue",
        "driveType": "FWD",
        "bodyType": "compact",
        "features": [
            "10.25\" Full Digital Cluster",
            "Blind Spot Detection",
            "Smart Key Entry",
            "Comfortable High Seating"
        ],
        "image": "images/genesis_g80.jpg",
        "description": "Affordable and stylish compact SUV with high visibility, spacious rear row, and easy parts availability."
    },
    {
        "id": 41,
        "brand": "BMW",
        "model": "5 Series (520i)",
        "year": 2023,
        "mileage": 15000,
        "price": 46500,
        "condition": "Used",
        "status": "Available",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "2.0L TwinPower Turbo",
        "color": "Alpine White",
        "driveType": "RWD",
        "bodyType": "sedan",
        "features": [
            "M Sport Package",
            "BMW Live Cockpit Professional",
            "Harman Kardon Surround",
            "Driving Assistant Professional"
        ],
        "image": "images/genesis_g80.jpg",
        "description": "Sourced from high-grade Korean corporate fleet. Immaculate service record with renowned German highway dynamics."
    },
    {
        "id": 42,
        "brand": "BMW",
        "model": "X5 (xDrive40i)",
        "year": 2023,
        "mileage": 21000,
        "price": 68000,
        "condition": "Used",
        "status": "Sold",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "3.0L Inline-6 Turbo (B58)",
        "color": "Carbon Black Metallic",
        "driveType": "AWD",
        "bodyType": "suv",
        "features": [
            "M Sport Exhaust",
            "Panoramic Sky Lounge LED Roof",
            "Air Suspension",
            "CraftedClarity Glass Controls"
        ],
        "image": "images/hyundai_palisade.jpg",
        "description": "The benchmark luxury sports activity vehicle. Equipped with BMW's legendary B58 engine and full premium Korean spec."
    },
    {
        "id": 43,
        "brand": "BMW",
        "model": "3 Series (320d)",
        "year": 2021,
        "mileage": 52000,
        "price": 27500,
        "condition": "Used",
        "status": "Available",
        "fuel": "Diesel",
        "transmission": "Automatic",
        "engine": "2.0L Turbo Diesel",
        "color": "Portimao Blue",
        "driveType": "RWD",
        "bodyType": "sedan",
        "features": [
            "M Aerodynamics Package",
            "Variable Sport Steering",
            "Laser Headlights",
            "Outstanding 18+ km/L Fuel Economy"
        ],
        "image": "images/genesis_g80.jpg",
        "description": "Iconic sports sedan with razor-sharp balance and exceptional real-world diesel long-distance cruising range."
    },
    {
        "id": 44,
        "brand": "Mercedes",
        "model": "E-Class (E250)",
        "year": 2023,
        "mileage": 17000,
        "price": 49000,
        "condition": "Used",
        "status": "Available",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "2.0L Turbo",
        "color": "Obsidian Black Metallic",
        "driveType": "RWD",
        "bodyType": "sedan",
        "features": [
            "Exclusive Luxury Package",
            "Widescreen Digital Cockpit",
            "64-Color Ambient Mood Lights",
            "Burmester Audio"
        ],
        "image": "images/genesis_g80.jpg",
        "description": "South Korea is the #1 market globally for the E-Class. Kept in pristine underground garage condition with total luxury poise."
    },
    {
        "id": 45,
        "brand": "Mercedes",
        "model": "GLC 300 4MATIC",
        "year": 2023,
        "mileage": 14000,
        "price": 54500,
        "condition": "Used",
        "status": "Sold",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "2.0L Turbo Mild-Hybrid",
        "color": "Polar White",
        "driveType": "AWD",
        "bodyType": "suv",
        "features": [
            "AMG Line Styling",
            "Off-Road Transparent Bonnet Cam",
            "Panoramic Sliding Roof",
            "Digital Light System"
        ],
        "image": "images/hyundai_palisade.jpg",
        "description": "Sophisticated compact luxury SUV uniting athletic stance with intuitive MBUX intelligence and confident AWD traction."
    },
    {
        "id": 46,
        "brand": "Mercedes",
        "model": "S-Class (S500L 4MATIC)",
        "year": 2022,
        "mileage": 28000,
        "price": 95000,
        "condition": "Used",
        "status": "Sold",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "3.0L Inline-6 Turbo EQ Boost",
        "color": "Onyx Black",
        "driveType": "AWD",
        "bodyType": "sedan",
        "features": [
            "Chauffeur Package",
            "Rear Axle Steering (10 Deg)",
            "3D Drivers Display",
            "Active Ambient Air Purifier"
        ],
        "image": "images/genesis_g80.jpg",
        "description": "The pinnacle of executive prestige. Long-wheelbase luxury chariot preserved to highest standards in Korea."
    },
    {
        "id": 47,
        "brand": "Volkswagen",
        "model": "Tiguan",
        "year": 2022,
        "mileage": 34000,
        "price": 24500,
        "condition": "Used",
        "status": "Available",
        "fuel": "Diesel",
        "transmission": "Automatic",
        "engine": "2.0L TDI",
        "color": "Pure White",
        "driveType": "FWD",
        "bodyType": "suv",
        "features": [
            "Prestige Trim",
            "IQ.Drive Travel Assist",
            "Digital Cockpit Pro",
            "Electric Easy Open Tailgate"
        ],
        "image": "images/hyundai_palisade.jpg",
        "description": "German family practicality with renowned high-torque TDI engine and bulletproof 7-speed DSG transmission."
    },
    {
        "id": 48,
        "brand": "Volkswagen",
        "model": "Arteon",
        "year": 2022,
        "mileage": 31000,
        "price": 28500,
        "condition": "Used",
        "status": "Sold",
        "fuel": "Diesel",
        "transmission": "Automatic",
        "engine": "2.0L TDI",
        "color": "Kings Red Metallic",
        "driveType": "AWD",
        "bodyType": "sedan",
        "features": [
            "R-Line Aerodynamics",
            "Frameless Fastback Windows",
            "Dynaudio Premium Sound",
            "DCC Adaptive Chassis"
        ],
        "image": "images/genesis_g80.jpg",
        "description": "Breathtaking 5-door gran turismo coupe styling with massive liftback cargo practicality and 4MOTION grip."
    },
    {
        "id": 49,
        "brand": "Toyota",
        "model": "Camry Hybrid",
        "year": 2023,
        "mileage": 22000,
        "price": 26000,
        "condition": "Used",
        "status": "Available",
        "fuel": "Hybrid",
        "transmission": "Automatic",
        "engine": "2.5L Dynamic Force Hybrid",
        "color": "Attitude Black",
        "driveType": "FWD",
        "bodyType": "hybrid",
        "features": [
            "Toyota Safety Sense 2.5+",
            "JBL 9-Speaker Audio",
            "EV Drive Mode",
            "Astonishing 20 km/L Real World Economy"
        ],
        "image": "images/genesis_g80.jpg",
        "description": "The gold standard of bulletproof hybrid engineering. Trusted worldwide for 500,000+ km service life without breakdown."
    },
    {
        "id": 50,
        "brand": "Toyota",
        "model": "RAV4 Hybrid",
        "year": 2023,
        "mileage": 18000,
        "price": 31500,
        "condition": "Used",
        "status": "Available",
        "fuel": "Hybrid",
        "transmission": "Automatic",
        "engine": "2.5L Hybrid E-Four AWD",
        "color": "Magnetic Gray Metallic",
        "driveType": "AWD",
        "bodyType": "hybrid",
        "features": [
            "Electric AWD (E-Four)",
            "Trail Mode",
            "Pre-Collision System",
            "Spacious 580L Cargo Trunk"
        ],
        "image": "images/hyundai_palisade.jpg",
        "description": "World's favorite hybrid SUV. Capable all-weather electronic 4WD with legendary Japanese reliability."
    },
    {
        "id": 51,
        "brand": "Hyundai",
        "model": "Avante (Elantra) N",
        "year": 2023,
        "mileage": 12000,
        "price": 26500,
        "condition": "Used",
        "status": "Sold",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "2.0L Turbo Flat Power (280 HP)",
        "color": "Performance Blue",
        "driveType": "FWD",
        "bodyType": "sedan",
        "features": [
            "N Corner Carving Differential (e-LSD)",
            "N Grin Shift (290 HP Overboost)",
            "Variable Exhaust Valve System",
            "N Light Bucket Seats"
        ],
        "image": "images/genesis_g80.jpg",
        "description": "Track-ready street weapon developed on the Nurburgring. Pops, crackles, and blistering cornering precision."
    },
    {
        "id": 52,
        "brand": "Kia",
        "model": "Ray",
        "year": 2022,
        "mileage": 31000,
        "price": 8900,
        "condition": "Used",
        "status": "Available",
        "fuel": "Gasoline",
        "transmission": "Automatic",
        "engine": "1.0L MPI",
        "color": "Milky Beige",
        "driveType": "FWD",
        "bodyType": "compact",
        "features": [
            "Pillarless Sliding Passenger Door",
            "Full Flat Folding Seats",
            "Surprising Limousine Rear Legroom",
            "City Parking Discount"
        ],
        "image": "images/kia_ev6.jpg",
        "description": "Korea's iconic Kei-style box mini car. Features a magical pillarless sliding door and cavernous interior room in a compact footprint."
    }
]
